# LUMIX fisheye model for 1K setting

#==============#
# Camera Model #
#==============#

Camera.name: "Razer kiyo"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 450.47198729
Camera.fy: 450.56062548
Camera.cx: 306.83766433
Camera.cy: 183.45145229

Camera.k1: 0.20086909 
Camera.k2: -1.19094546
Camera.p1: 0.00327047
Camera.p2: -0.01362785
Camera.k3: 2.01310632

Camera.fps: 30.0
Camera.cols: 630
Camera.rows: 394

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#========================#
# Initializer Parameters #
#========================#

Initializer.scaling_factor: 5.0
