# LUMIX fisheye model for 1K setting

#==============#
# Camera Model #
#==============#

Camera.name: "LUMIX DMC-GX8 8mm fisheye 1K"
Camera.setup: "monocular"
Camera.model: "fisheye"

Camera.fx: 441.730011169
Camera.fy: 442.520822476
Camera.cx: 480.35667528
Camera.cy: 275.490228646

Camera.k1: -3.068701296607466433e-02
Camera.k2: -3.343454364086094217e-03
Camera.k3: -2.881735840896060968e-03
Camera.k4: -5.917420310474077278e-04

Camera.fps: 30.0
Camera.cols: 960
Camera.rows: 540

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#========================#
# Initializer Parameters #
#========================#

Initializer.scaling_factor: 5.0
